[package]
name = "touchcue"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
miette = { workspace = true, features = ["fancy-no-backtrace"] }
thiserror.workspace = true
tokio = { workspace = true, features = [
  "macros",
  "rt",
  "rt-multi-thread",
  "sync",
  "time",
] }
tokio-util.workspace = true
touchcue-appinfo.workspace = true
touchcue-core.workspace = true
touchcue-detect.workspace = true
touchcue-ipc.workspace = true
touchcue-ui.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
usage.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
rustix = { workspace = true, features = ["process", "stdio"] }
touchcue-hooks.workspace = true
tokio = { workspace = true, features = [
  "fs",
  "io-std",
  "io-util",
  "net",
  "process",
  "signal",
] }

[dev-dependencies]
tempfile.workspace = true
tokio = { workspace = true, features = ["macros", "rt", "test-util"] }

[target.'cfg(target_os = "linux")'.dev-dependencies]
rustix = { workspace = true, features = ["process"] }

[lints]
workspace = true
