//! Repository automation, run as `cargo xtask <task>`.

use std::{env, fs, path::Path};

use anyhow::{Context, Result, bail};
use touchcue::cli::Cli;

const USAGE_SPEC: &str = "touchcue.usage.kdl";

fn main() -> Result<()> {
    match env::args().nth(1).as_deref() {
        Some("render") => render(),
        _ => bail!("usage: cargo xtask render"),
    }
}

/// Writes the usage spec of the `touchcue` CLI to the workspace root.
///
/// The spec omits the crate version so that a version bump leaves every
/// generated file unchanged.
fn render() -> Result<()> {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .context("xtask manifest directory has no parent")?;
    let mut spec = String::from("// @generated by usage-rs from the touchcue CLI definition\n");
    for line in Cli::to_kdl().lines() {
        if !line.starts_with("version ") {
            spec.push_str(line);
            spec.push('\n');
        }
    }
    // Keep exactly one trailing newline.
    spec.truncate(spec.trim_end().len());
    spec.push('\n');
    let path = root.join(USAGE_SPEC);
    fs::write(&path, spec).with_context(|| format!("writing {}", path.display()))
}
