#compdef touchcue
# @generated by usage-cli from touchcue.usage.kdl
local curcontext="$curcontext"

_touchcue() {
  emulate -L zsh
  typeset -A opt_args
  local curcontext="$curcontext" cache_policy

  if ! type -p usage &> /dev/null; then
      echo >&2
      echo "Error: usage CLI not found. This is required for completions to work in touchcue." >&2
      echo "See https://usage.jdx.dev for more information." >&2
      return 1
  fi

  local spec_dir="${XDG_CACHE_HOME:-$HOME/.cache}/usage"
  [[ -d "$spec_dir" ]] || mkdir -p -m 700 "$spec_dir"
  local spec_file="$spec_dir/usage__usage_spec_touchcue.spec"
  cat >| "$spec_file" <<'__USAGE_EOF__'
name touchcue
bin touchcue
about "Shows who is waiting for your security key touch"
unknown_flags error
args_override_self #false
subcommand_required #true
flag --config help="Configuration file [default: $XDG_CONFIG_HOME/touchcue/config.toml]" global=#true {
    arg <PATH>
}
flag "-v --verbose" help="Log more: -v for info, -vv for debug; TOUCHCUE_LOG overrides it" var=#true global=#true count=#true
flag "-h --help" help="Print help" action=help builtin=#true
flag "-V --version" help="Print version" action=version builtin=#true
complete path type=path
cmd run help="Run the daemon in the foreground" {
    flag "-h --help" help="Print help" action=help builtin=#true
}
cmd check help="Check the configuration, desktop capabilities and devices" {
    flag "-h --help" help="Print help" action=help builtin=#true
}
cmd list-devices help="List the connected FIDO devices" {
    flag "-h --help" help="Print help" action=help builtin=#true
}
cmd trace help="Print touch detection signals until interrupted" {
    flag "-h --help" help="Print help" action=help builtin=#true
}
cmd gpg subcommand_required=#true help="Set up touch detection for gpg and ssh through gpg-agent" {
    flag "-h --help" help="Print help" action=help builtin=#true
    cmd install help="Make gpg-agent run touchcue as its scdaemon" {
        flag "-h --help" help="Print help" action=help builtin=#true
    }
    cmd uninstall help="Stop gpg-agent from running touchcue as its scdaemon" {
        flag --restore-backup help="Replace gpg-agent.conf with the backup taken by install, then delete the backup"
        flag "-h --help" help="Print help" action=help builtin=#true
    }
}
cmd askpass help="Answer an OpenSSH askpass prompt" {
    long_help #"""
Answer an OpenSSH askpass prompt

OpenSSH runs the `SSH_ASKPASS` program with no extra arguments, so point it at a link to touchcue named `touchcue-askpass`. `touchcue askpass` passes every argument after it through unparsed.
"""#
    flag "-h --help" help="Print help" action=help builtin=#true
    arg "[MESSAGE]…" help="The prompt OpenSSH passes" required=#false double_dash=automatic var=#true
}
__USAGE_EOF__
  local -a values=() descs=() inserts=()
  local needs_menu=0 line usage_err=
  while IFS= read -r line; do
    if [[ "$line" == $'\x1f'* ]]; then
      usage_err="${line#?}"
      continue
    fi
    local -a parts=("${(@ps:\t:)line}")
    values+=("${parts[1]}")
    descs+=("${parts[2]}")
    inserts+=("${parts[3]}")
    [[ "${parts[3]}" == "'"* ]] && needs_menu=1
  done < <(
    { _usage_err="$(command usage complete-word --shell zsh -f "$spec_file" --cword=$((CURRENT - 1)) -- "${(Q)words[@]}" 2>&1 >&3 3>&-)"; } 3>&1
    (( $? )) || _usage_err=
    for _usage_l in "${(@f)_usage_err}"; do
      [[ "$_usage_l" == \[[A-Z]*\]* ]] && continue
      _usage_l="${_usage_l#"${_usage_l%%[![:space:]]*}"}"
      _usage_l="${_usage_l#Error:}"
      _usage_l="${_usage_l#"${_usage_l%%[![:space:]]*}"}"
      _usage_l="${_usage_l#× }"
      [[ -z "$_usage_l" || ( "$_usage_l" == *::* && "$_usage_l" != *' '* ) ]] && continue
      print -r -- $'\x1f'"$_usage_l"
      break
    done
  )
  [[ -n "$usage_err" ]] && _message -r "usage: ${usage_err//\%/%%}"
  (( needs_menu )) && compstate[insert]=menu
  if (( ${#inserts[@]} )); then
    local -a _usage_display=()
    local _usage_i _usage_max=0 _usage_v _usage_pad
    for _usage_v in "${values[@]}"; do
      (( ${#_usage_v} > _usage_max )) && _usage_max=${#_usage_v}
    done
    for ((_usage_i=1; _usage_i<=${#values[@]}; _usage_i++)); do
      if [[ -n "${descs[_usage_i]}" ]]; then
        _usage_pad=$(( _usage_max - ${#values[_usage_i]} ))
        _usage_display+=("${values[_usage_i]}${(l:_usage_pad:: :)}  -- ${descs[_usage_i]}")
      else
        _usage_display+=("${values[_usage_i]}")
      fi
    done
    compadd -l -d _usage_display -U -Q -S '' -a inserts
  fi
  return 0
}

if [ "$funcstack[1]" = "_touchcue" ]; then
    _touchcue "$@"
else
    compdef _touchcue touchcue
fi

# vim: noet ci pi sts=0 sw=4 ts=4
