# @generated by usage-cli from touchcue.usage.kdl
# Requires bash-completion (https://github.com/scop/bash-completion), which must be
# sourced before this script.
_touchcue() {
    if ! type -P usage &> /dev/null; then
        echo >&2
        echo "Error: usage CLI not found. This is required for completions to work in touchcue." >&2
        echo "See https://usage.jdx.dev for more information." >&2
        return 1
    fi
    if ! declare -F _init_completion > /dev/null 2>&1; then
        echo >&2
        echo "Error: bash-completion is required for touchcue completions but was not loaded." >&2
        echo "Install it from your package manager and source it before this script." >&2
        return 1
    fi

	local cur prev words cword comp_args
    # `=` and `:` stay inside the word so complete-word sees `--out=a` as one word
    # rather than `--out`, `=`, `a`.
    _init_completion -n := -- "$@" || return
    local spec_dir="${XDG_CACHE_HOME:-$HOME/.cache}/usage"
    [[ -d "$spec_dir" ]] || mkdir -p -m 700 "$spec_dir"
    local spec_file="$spec_dir/usage__usage_spec_touchcue.spec"
    cat >| "$spec_file" <<'__USAGE_EOF__'
name touchcue
bin touchcue
about "Shows who is waiting for your security key touch"
unknown_flags error
args_override_self #false
subcommand_required #true
flag --config help="Configuration file [default: $XDG_CONFIG_HOME/touchcue/config.toml]" global=#true {
    arg <PATH>
}
flag "-v --verbose" help="Log more: -v for info, -vv for debug; TOUCHCUE_LOG overrides it" var=#true global=#true count=#true
flag "-h --help" help="Print help" action=help builtin=#true
flag "-V --version" help="Print version" action=version builtin=#true
complete path type=path
cmd run help="Run the daemon in the foreground" {
    flag "-h --help" help="Print help" action=help builtin=#true
}
cmd check help="Check the configuration, desktop capabilities and devices" {
    flag "-h --help" help="Print help" action=help builtin=#true
}
cmd list-devices help="List the connected FIDO devices" {
    flag "-h --help" help="Print help" action=help builtin=#true
}
cmd trace help="Print touch detection signals until interrupted" {
    flag "-h --help" help="Print help" action=help builtin=#true
}
cmd gpg subcommand_required=#true help="Set up touch detection for gpg and ssh through gpg-agent" {
    flag "-h --help" help="Print help" action=help builtin=#true
    cmd install help="Make gpg-agent run touchcue as its scdaemon" {
        flag "-h --help" help="Print help" action=help builtin=#true
    }
    cmd uninstall help="Stop gpg-agent from running touchcue as its scdaemon" {
        flag --restore-backup help="Replace gpg-agent.conf with the backup taken by install, then delete the backup"
        flag "-h --help" help="Print help" action=help builtin=#true
    }
}
cmd askpass help="Answer an OpenSSH askpass prompt" {
    long_help #"""
Answer an OpenSSH askpass prompt

OpenSSH runs the `SSH_ASKPASS` program with no extra arguments, so point it at a link to touchcue named `touchcue-askpass`. `touchcue askpass` passes every argument after it through unparsed.
"""#
    flag "-h --help" help="Print help" action=help builtin=#true
    arg "[MESSAGE]…" help="The prompt OpenSSH passes" required=#false double_dash=automatic var=#true
}
__USAGE_EOF__
    # stderr is discarded: a line that doesn't parse (`touchcue help <Tab>`) makes
    # complete-word fail, and its error would be printed over the prompt.
    # Complete the text before the cursor, as `$cur` holds it: with the cursor in `--out=a|X`
    # the value typed so far is `a`, not `aX`.
    words[cword]="$cur"
    # shellcheck disable=SC2207
	COMPREPLY=($(compgen -W "$(command usage complete-word --shell bash -f "$spec_file" --cword="$cword" -- "${words[@]}" 2>/dev/null)" -- "$cur"))
	# Readline only replaces the text after the last word break, so strip the part of
	# `$cur` up to its last `:` or `=` from each candidate (what __ltrim_colon_completions
	# does for `:` alone).
	local breaks="${COMP_WORDBREAKS//[^:=]/}"
	# An empty COMPREPLY is left alone: before bash 4.4 the rewrite below would turn it into
	# one empty candidate.
	if ((${#COMPREPLY[@]})) && [[ -n "$breaks" && "$cur" == *["$breaks"]* ]]; then
		local break_prefix="${cur%"${cur##*["$breaks"]}"}"
		COMPREPLY=("${COMPREPLY[@]#"$break_prefix"}")
	fi
    # shellcheck disable=SC2181
    if [[ $? -ne 0 ]]; then
        unset COMPREPLY
    fi
    return 0
}

if [[ "${BASH_VERSINFO[0]}" -eq 4 && "${BASH_VERSINFO[1]}" -ge 4 || "${BASH_VERSINFO[0]}" -gt 4 ]]; then
    shopt -u hostcomplete && complete -o nospace -o bashdefault -o nosort -F _touchcue touchcue
else
    shopt -u hostcomplete && complete -o nospace -o bashdefault -F _touchcue touchcue
fi
# vim: noet ci pi sts=0 sw=4 ts=4 ft=sh
