# @generated by usage-cli from touchcue.usage.kdl
module _touchcue_completions {
    const _usage_spec_touchcue = r##'name touchcue
bin touchcue
about "Shows who is waiting for your security key touch"
unknown_flags error
args_override_self #false
subcommand_required #true
flag --config help="Configuration file [default: $XDG_CONFIG_HOME/touchcue/config.toml]" global=#true {
    arg <PATH>
}
flag "-v --verbose" help="Log more: -v for info, -vv for debug; TOUCHCUE_LOG overrides it" var=#true global=#true count=#true
flag "-h --help" help="Print help" action=help builtin=#true
flag "-V --version" help="Print version" action=version builtin=#true
complete path type=path
cmd run help="Run the daemon in the foreground" {
    flag "-h --help" help="Print help" action=help builtin=#true
}
cmd check help="Check the configuration, desktop capabilities and devices" {
    flag "-h --help" help="Print help" action=help builtin=#true
}
cmd list-devices help="List the connected FIDO devices" {
    flag "-h --help" help="Print help" action=help builtin=#true
}
cmd trace help="Print touch detection signals until interrupted" {
    flag "-h --help" help="Print help" action=help builtin=#true
}
cmd gpg subcommand_required=#true help="Set up touch detection for gpg and ssh through gpg-agent" {
    flag "-h --help" help="Print help" action=help builtin=#true
    cmd install help="Make gpg-agent run touchcue as its scdaemon" {
        flag "-h --help" help="Print help" action=help builtin=#true
    }
    cmd uninstall help="Stop gpg-agent from running touchcue as its scdaemon" {
        flag --restore-backup help="Replace gpg-agent.conf with the backup taken by install, then delete the backup"
        flag "-h --help" help="Print help" action=help builtin=#true
    }
}
cmd askpass help="Answer an OpenSSH askpass prompt" {
    long_help #"""
Answer an OpenSSH askpass prompt

OpenSSH runs the `SSH_ASKPASS` program with no extra arguments, so point it at a link to touchcue named `touchcue-askpass`. `touchcue askpass` passes every argument after it through unparsed.
"""#
    flag "-h --help" help="Print help" action=help builtin=#true
    arg "[MESSAGE]…" help="The prompt OpenSSH passes" required=#false double_dash=automatic var=#true
}
'##
    def touchcue_completer [spans: list<string>] {
        let spec_dir = ($env.XDG_CACHE_HOME? | default ($nu.home-dir? | default $nu.home-path? | path join ".cache") | path join "usage")
        if not ($spec_dir | path exists) {
            mkdir $spec_dir
            if $nu.os-info.family != "windows" { ^chmod 0700 $spec_dir }
        }
        let spec_file = ($spec_dir | path join $"usage__usage_spec_touchcue.spec")
        $_usage_spec_touchcue | save -f $spec_file

        # `complete` captures stderr and the exit code: a line that doesn't
        # parse makes complete-word fail, and its error would be printed over
        # the prompt.
        (^usage complete-word -f $spec_file --shell nu -- ...$spans | complete).stdout
        | lines
        | each {|it| $it | split column "\t" | rename value description | into record }
    }

    @complete touchcue_completer
    export extern touchcue []
}


# if "usage" is not installed show an error
if (which usage | is-empty) {
    return (error make {
        msg: "Error: usage CLI not found. This is required for completions to work in touchcue.",
        help: "See https://usage.jdx.dev for more information."
    })
}
use _touchcue_completions *
