# @generated by usage-cli from touchcue.usage.kdl

# if "usage" is not installed show an error
if ! type -P usage &> /dev/null
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in touchcue." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
end

set _usage_spec_touchcue 'name touchcue
bin touchcue
about "Shows who is waiting for your security key touch"
unknown_flags error
args_override_self #false
subcommand_required #true
flag --config help="Configuration file [default: $XDG_CONFIG_HOME/touchcue/config.toml]" global=#true {
    arg <PATH>
}
flag "-v --verbose" help="Log more: -v for info, -vv for debug; TOUCHCUE_LOG overrides it" var=#true global=#true count=#true
flag "-h --help" help="Print help" action=help builtin=#true
flag "-V --version" help="Print version" action=version builtin=#true
complete path type=path
cmd run help="Run the daemon in the foreground" {
    flag "-h --help" help="Print help" action=help builtin=#true
}
cmd check help="Check the configuration, desktop capabilities and devices" {
    flag "-h --help" help="Print help" action=help builtin=#true
}
cmd list-devices help="List the connected FIDO devices" {
    flag "-h --help" help="Print help" action=help builtin=#true
}
cmd trace help="Print touch detection signals until interrupted" {
    flag "-h --help" help="Print help" action=help builtin=#true
}
cmd gpg subcommand_required=#true help="Set up touch detection for gpg and ssh through gpg-agent" {
    flag "-h --help" help="Print help" action=help builtin=#true
    cmd install help="Make gpg-agent run touchcue as its scdaemon" {
        flag "-h --help" help="Print help" action=help builtin=#true
    }
    cmd uninstall help="Stop gpg-agent from running touchcue as its scdaemon" {
        flag --restore-backup help="Replace gpg-agent.conf with the backup taken by install, then delete the backup"
        flag "-h --help" help="Print help" action=help builtin=#true
    }
}
cmd askpass help="Answer an OpenSSH askpass prompt" {
    long_help #"""
Answer an OpenSSH askpass prompt

OpenSSH runs the `SSH_ASKPASS` program with no extra arguments, so point it at a link to touchcue named `touchcue-askpass`. `touchcue askpass` passes every argument after it through unparsed.
"""#
    flag "-h --help" help="Print help" action=help builtin=#true
    arg "[MESSAGE]…" help="The prompt OpenSSH passes" required=#false double_dash=automatic var=#true
}
'
set -l spec_dir (if set -q XDG_CACHE_HOME; echo $XDG_CACHE_HOME; else; echo $HOME/.cache; end)/usage
test -d "$spec_dir"; or mkdir -p -m 700 "$spec_dir"
set -l spec_file "$spec_dir/usage__usage_spec_touchcue.spec"
echo $_usage_spec_touchcue > "$spec_file"

# stderr is discarded: a line that doesn't parse (`touchcue help <Tab>`) makes
# complete-word fail, and its error would be printed over the prompt.
# The word being completed is cut at the cursor (`-c`) and unquoted, so
# `'prod<Tab>` and `sub\ dir/<Tab>` match the same values as their bare
# spellings; fish re-quotes whatever it inserts.
if commandline -x >/dev/null 2>&1
    complete -xc touchcue -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -xpc) (commandline -ct | string unescape) 2>/dev/null)"
else
    complete -xc touchcue -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -opc) (commandline -ct | string unescape) 2>/dev/null)"
end
