# @generated by usage-cli from touchcue.usage.kdl

if (-not (Get-Command 'usage' -ErrorAction SilentlyContinue)) {
    Write-Warning "Error: usage CLI not found. This is required for completions to work in touchcue."
    Write-Warning "See https://usage.jdx.dev for more information."
    return
}

Register-ArgumentCompleter -Native -CommandName 'touchcue' -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)

    $tmpDir = if ($env:TEMP) { $env:TEMP } else { [System.IO.Path]::GetTempPath() }
    $specFile = Join-Path $tmpDir "usage__usage_spec_touchcue.kdl"

    'name touchcue
bin touchcue
about "Shows who is waiting for your security key touch"
unknown_flags error
args_override_self #false
subcommand_required #true
flag --config help="Configuration file [default: $XDG_CONFIG_HOME/touchcue/config.toml]" global=#true {
    arg <PATH>
}
flag "-v --verbose" help="Log more: -v for info, -vv for debug; TOUCHCUE_LOG overrides it" var=#true global=#true count=#true
flag "-h --help" help="Print help" action=help builtin=#true
flag "-V --version" help="Print version" action=version builtin=#true
complete path type=path
cmd run help="Run the daemon in the foreground" {
    flag "-h --help" help="Print help" action=help builtin=#true
}
cmd check help="Check the configuration, desktop capabilities and devices" {
    flag "-h --help" help="Print help" action=help builtin=#true
}
cmd list-devices help="List the connected FIDO devices" {
    flag "-h --help" help="Print help" action=help builtin=#true
}
cmd trace help="Print touch detection signals until interrupted" {
    flag "-h --help" help="Print help" action=help builtin=#true
}
cmd gpg subcommand_required=#true help="Set up touch detection for gpg and ssh through gpg-agent" {
    flag "-h --help" help="Print help" action=help builtin=#true
    cmd install help="Make gpg-agent run touchcue as its scdaemon" {
        flag "-h --help" help="Print help" action=help builtin=#true
    }
    cmd uninstall help="Stop gpg-agent from running touchcue as its scdaemon" {
        flag --restore-backup help="Replace gpg-agent.conf with the backup taken by install, then delete the backup"
        flag "-h --help" help="Print help" action=help builtin=#true
    }
}
cmd askpass help="Answer an OpenSSH askpass prompt" {
    long_help #"""
Answer an OpenSSH askpass prompt

OpenSSH runs the `SSH_ASKPASS` program with no extra arguments, so point it at a link to touchcue named `touchcue-askpass`. `touchcue askpass` passes every argument after it through unparsed.
"""#
    flag "-h --help" help="Print help" action=help builtin=#true
    arg "[MESSAGE]…" help="The prompt OpenSSH passes" required=#false double_dash=automatic var=#true
}
' | Out-File -FilePath $specFile -Encoding utf8

    $words = $commandAst.CommandElements | ForEach-Object { $_.ToString() }
    if ($words.Count -lt 1) {
        $words = @('touchcue')
    }

    $completions = & 'usage' complete-word --shell powershell -f "$specFile" -- @words $wordToComplete 2>$null

    if ($completions) {
        $completions | ForEach-Object {
            $parts = $_ -split "`t", 2
            $completion = $parts[0]
            $description = if ($parts.Count -gt 1) { $parts[1] } else { '' }

            [System.Management.Automation.CompletionResult]::new(
                $completion,
                $completion,
                'ParameterValue',
                $description
            )
        }
    }
}
